/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import kontrol.cruddosen;

/**
 *
 * @author Rangga
 */
public class dosen extends javax.swing.JFrame {
    cruddosen CRUDdosen;
    /**
     * Creates new form dosen
     */
    public dosen() throws SQLException {
        initComponents();
        CRUDdosen = new cruddosen(this);
        CRUDdosen.table();
        tabeldosen1.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtjbtn = new javax.swing.JTextField();
        txtnip = new javax.swing.JTextField();
        txtnmadsn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldosen1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tambahdsn = new javax.swing.JButton();
        updatedsn = new javax.swing.JButton();
        deletedsn = new javax.swing.JButton();
        backdsn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtjbtn.setBorder(null);
        jPanel1.add(txtjbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, 30));

        txtnip.setBorder(null);
        jPanel1.add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, 20));

        txtnmadsn.setBorder(null);
        jPanel1.add(txtnmadsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, 20));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabeldosen1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabeldosen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldosen1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldosen1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 390, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BERANDA DOSEN (2) (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        tambahdsn.setText("tambah");
        tambahdsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahdsnActionPerformed(evt);
            }
        });
        jPanel1.add(tambahdsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 250, 90, 40));

        updatedsn.setText("update");
        updatedsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedsnActionPerformed(evt);
            }
        });
        jPanel1.add(updatedsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 40));

        deletedsn.setText("delete");
        deletedsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedsnActionPerformed(evt);
            }
        });
        jPanel1.add(deletedsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 300, 80, 40));

        backdsn.setText("back");
        backdsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backdsnActionPerformed(evt);
            }
        });
        jPanel1.add(backdsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahdsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahdsnActionPerformed
        CRUDdosen.insertdosen();
        CRUDdosen.table();
        CRUDdosen.reset();
    }//GEN-LAST:event_tambahdsnActionPerformed

    private void updatedsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedsnActionPerformed
        CRUDdosen.updatedosen();
        CRUDdosen.table();
        CRUDdosen.reset();
    }//GEN-LAST:event_updatedsnActionPerformed

    private void deletedsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedsnActionPerformed
        CRUDdosen.deletedosen();
        CRUDdosen.table();
        CRUDdosen.reset();
    }//GEN-LAST:event_deletedsnActionPerformed

    private void backdsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backdsnActionPerformed
        Menuadmin ma = new Menuadmin();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backdsnActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
       
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabeldosen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldosen1MouseClicked
        CRUDdosen.fielddosen(tabeldosen1.getSelectedRow());
    }//GEN-LAST:event_tabeldosen1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new dosen().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(dosen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backdsn;
    private javax.swing.JButton deletedsn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldosen1;
    private javax.swing.JButton tambahdsn;
    private javax.swing.JTextField txtjbtn;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtnmadsn;
    private javax.swing.JButton updatedsn;
    // End of variables declaration//GEN-END:variables

    public JButton getBackdsn() {
        return backdsn;
    }

    public JButton getDeletedsn() {
        return deletedsn;
    }

    public JTable gettabeldosen1() {
        return tabeldosen1;
    }

    public JButton getTambahdsn() {
        return tambahdsn;
    }

    public JTextField getTxtjbtn() {
        return txtjbtn;
    }

    public JTextField getTxtnip() {
        return txtnip;
    }

    public JTextField getTxtnmadsn() {
        return txtnmadsn;
    }

    public JButton getUpdatedsn() {
        return updatedsn;
    }

}
