/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.*;
import javax.swing.JOptionPane;
import databases.Database;

/**
 *
 * @author Rangga
 */
public class Loginadmin extends javax.swing.JFrame {

    /**
     * Creates new form Loginadmin
     */
    public Loginadmin() {
        initComponents();
    }
    
    private static final String Admin_username = "admin";
    private static final String Admin_password = "1234";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        nipdosen = new javax.swing.JTextField();
        passdosen = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        Loginadmin = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nipdosen.setBorder(null);
        jPanel1.add(nipdosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 100, 20));

        passdosen.setBorder(null);
        passdosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passdosenActionPerformed(evt);
            }
        });
        jPanel1.add(passdosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGIN DOSEN (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        Loginadmin.setText("jButton1");
        Loginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginadminActionPerformed(evt);
            }
        });
        jPanel1.add(Loginadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 90, 30));

        back.setText("jButton1");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passdosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passdosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passdosenActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       HalamanLogin hl = new HalamanLogin();
       hl.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void LoginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginadminActionPerformed
        try {
            if (nipdosen.getText().equals("") || passdosen.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "DATA TIDAK BOLEH KOSONG");
            }else {
                if (nipdosen.getText().equals("admin") && passdosen.getText().equals("1234")) {
                    JOptionPane.showMessageDialog(null, "Selamat datang, Admin!");
                    this.setVisible(false);
                    new Menuadmin().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Login gagal: Username atau password salah.");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Login gagal: " + e.getMessage());
        }


    }//GEN-LAST:event_LoginadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginadmin;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nipdosen;
    private javax.swing.JPasswordField passdosen;
    // End of variables declaration//GEN-END:variables
}
