/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import kontrol.crudmatkul;
import model.tabelmatkul;
/**
 *
 * @author Rangga
 */
public class matakuliah extends javax.swing.JFrame {
crudmatkul CRUDmatkul;

    /**
     * Creates new form matakuliah
     */
    public matakuliah() throws SQLException {
        initComponents();
        CRUDmatkul = new crudmatkul(this);
        CRUDmatkul.table();
        Tablematkul.getTableHeader().setResizingAllowed(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablematkul = new javax.swing.JTable();
        kode_matkul = new javax.swing.JTextField();
        nama_matkul = new javax.swing.JTextField();
        sks = new javax.swing.JTextField();
        Semester = new javax.swing.JTextField();
        Tahunajaran = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Create1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tablematkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode_Matkul", "Nama_Matkul", "SKS", "Semester", "Tahun_Ajaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tablematkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablematkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablematkul);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 400, 260));

        kode_matkul.setBorder(null);
        jPanel1.add(kode_matkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 130, 30));

        nama_matkul.setBorder(null);
        jPanel1.add(nama_matkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, 30));

        sks.setBorder(null);
        jPanel1.add(sks, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 130, 30));

        Semester.setBorder(null);
        jPanel1.add(Semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, 30));

        Tahunajaran.setBorder(null);
        jPanel1.add(Tahunajaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 350));

        Create1.setText("tambah");
        Create1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create1ActionPerformed(evt);
            }
        });
        jPanel1.add(Create1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, 30));

        update1.setText("update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jPanel1.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 80, 40));

        back1.setText("back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 70, -1));

        delete1.setText("deleta");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 310, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Create1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create1ActionPerformed
        CRUDmatkul.insertMataKuliah();
        CRUDmatkul.table();
        CRUDmatkul.reset();
    }//GEN-LAST:event_Create1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        CRUDmatkul.update();
        CRUDmatkul.table();
        CRUDmatkul.reset();
    }//GEN-LAST:event_update1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        Menuadmin ma = new Menuadmin();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back1ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        CRUDmatkul.delete();
        CRUDmatkul.table();
        CRUDmatkul.reset();
    }//GEN-LAST:event_delete1ActionPerformed

    private void TablematkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablematkulMouseClicked
        CRUDmatkul.field(Tablematkul.getSelectedRow());
    }//GEN-LAST:event_TablematkulMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new matakuliah().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(matakuliah.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create1;
    private javax.swing.JTextField Semester;
    private javax.swing.JTable Tablematkul;
    private javax.swing.JTextField Tahunajaran;
    private javax.swing.JButton back1;
    private javax.swing.JButton delete1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kode_matkul;
    private javax.swing.JTextField nama_matkul;
    private javax.swing.JTextField sks;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables

    public JButton getCreate1() {
        return Create1;
    }

    public JButton getBack1() {
        return back1;
    }

    public JButton getDelete1() {
        return delete1;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JTextField getKode_matkul() {
        return kode_matkul;
    }

    public JTextField getNama_matkul() {
        return nama_matkul;
    }

    public JTextField getSks() {
        return sks;
    }

    public JButton getUpdate1() {
        return update1;
    }

    public JTable getTablematkul() {
        return Tablematkul;
    }

    public JTextField getSemester() {
        return Semester;
    }

    public JTextField getTahunajaran() {
        return Tahunajaran;
    }
    
    
}


