/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.sql.*;
import databases.Database;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rangga
 */
public class Menuadmin extends javax.swing.JFrame {

    /**
     * Creates new form Menuadmin
     * @param jTable1
     */
            
    public Menuadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        datamatkul = new javax.swing.JButton();
        datamahasiswa = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        datadosen = new javax.swing.JButton();
        krs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN ADMIN (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        datamatkul.setText("jButton1");
        datamatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamatkulActionPerformed(evt);
            }
        });
        jPanel1.add(datamatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 40));

        datamahasiswa.setText("jButton3");
        datamahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamahasiswaActionPerformed(evt);
            }
        });
        jPanel1.add(datamahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 140, 40));

        back1.setText("jButton1");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 273, 90, 30));

        datadosen.setText("jButton2");
        datadosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datadosenActionPerformed(evt);
            }
        });
        jPanel1.add(datadosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, 30));

        krs.setText("jButton1");
        krs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krsActionPerformed(evt);
            }
        });
        jPanel1.add(krs, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 213, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datamatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamatkulActionPerformed
        try {
            matakuliah mk = new matakuliah();
            mk.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Menuadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datamatkulActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        HalamanLogin hl = new HalamanLogin();
        hl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back1ActionPerformed

    private void datadosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datadosenActionPerformed
        try {
            dosen dsn = new dosen();
            dsn.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Menuadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datadosenActionPerformed

    private void krsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krsActionPerformed
        menukrs mk = new menukrs();
        mk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_krsActionPerformed

    private void datamahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamahasiswaActionPerformed
        new menuMahasiswa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datamahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back1;
    private javax.swing.JButton datadosen;
    private javax.swing.JButton datamahasiswa;
    private javax.swing.JButton datamatkul;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton krs;
    // End of variables declaration//GEN-END:variables
}
