/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import kontrol.crudmahasiswa;

/**
 *
 * @author Rangga
 */
public class menuMahasiswa extends javax.swing.JFrame {
crudmahasiswa CRUDmahasiswa;
    /**
     * Creates new form Mahasiswa
     */
    public menuMahasiswa() {
        initComponents(); 
        CRUDmahasiswa = new crudmahasiswa(this);
        CRUDmahasiswa.table();
        tablemahas.getTableHeader().setResizingAllowed(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnim = new javax.swing.JTextField();
        Namamahasiswa = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        notelp = new javax.swing.JTextField();
        Jenis_Kelaminm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemahas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tambahm = new javax.swing.JButton();
        updatem = new javax.swing.JButton();
        deletem = new javax.swing.JButton();
        backm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnimActionPerformed(evt);
            }
        });
        jPanel1.add(txtnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, 30));
        jPanel1.add(Namamahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 98, 180, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 180, 30));
        jPanel1.add(notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, 30));
        jPanel1.add(Jenis_Kelaminm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 30));

        tablemahas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nim", "Nama", "Jenis_Kelamin", "Alamat", "No_telp"
            }
        ));
        tablemahas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemahasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemahas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 400, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BERANDA MAHASISWA (3) (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        tambahm.setText("tambah");
        tambahm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahmActionPerformed(evt);
            }
        });
        jPanel1.add(tambahm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        updatem.setText("update");
        updatem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemActionPerformed(evt);
            }
        });
        jPanel1.add(updatem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        deletem.setText("delete");
        deletem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletemActionPerformed(evt);
            }
        });
        jPanel1.add(deletem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        backm.setText("back");
        backm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backmActionPerformed(evt);
            }
        });
        jPanel1.add(backm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahmActionPerformed
        CRUDmahasiswa.insertMataKuliah();
        CRUDmahasiswa.table();
        CRUDmahasiswa.reset();
    }//GEN-LAST:event_tambahmActionPerformed

    private void txtnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnimActionPerformed
        
    }//GEN-LAST:event_txtnimActionPerformed

    private void updatemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemActionPerformed
        CRUDmahasiswa.update();
        CRUDmahasiswa.table();
        CRUDmahasiswa.reset();
    }//GEN-LAST:event_updatemActionPerformed

    private void deletemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletemActionPerformed
        CRUDmahasiswa.delete();
        CRUDmahasiswa.table();
        CRUDmahasiswa.reset();
    }//GEN-LAST:event_deletemActionPerformed

    private void backmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backmActionPerformed
        Menuadmin ma = new Menuadmin();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backmActionPerformed

    private void tablemahasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemahasMouseClicked
        CRUDmahasiswa.field(tablemahas.getSelectedRow());
    }//GEN-LAST:event_tablemahasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jenis_Kelaminm;
    private javax.swing.JTextField Namamahasiswa;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton backm;
    private javax.swing.JButton deletem;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField notelp;
    private javax.swing.JTable tablemahas;
    private javax.swing.JButton tambahm;
    private javax.swing.JTextField txtnim;
    private javax.swing.JButton updatem;
    // End of variables declaration//GEN-END:variables

    public JTextField getJenis_Kelaminm() {
        return Jenis_Kelaminm;
    }

    public JTextField getNamamahasiswa() {
        return Namamahasiswa;
    }

    public JTextField gettxtnim() {
        return txtnim;
    }

    public JTextField getAlamat() {
        return alamat;
    }

    public JButton getBackm() {
        return backm;
    }

    public JButton getDeletem() {
        return deletem;
    }

    public JTextField getNotelp() {
        return notelp;
    }

    public JButton getTambahm() {
        return tambahm;
    }

    public JButton getUpdatem() {
        return updatem;
    }

    public JTable getTablemahas() {
        return tablemahas;
    }


}
